### PR TITLE
Statistics module PSR-2 / XHTML / CSS

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by tvdijen** [comment]
Adresses #458

**Comment by thijskh** [comment]
Thanks! I've rebased to change the author to you and remove the several merge commits, to keep the history a bit cleaner; and then merged to master.

**Comment by tvdijen** [comment]
How did you remove those merge commits? I tried to figure that out, but didn't manage

**Comment by thijskh** [comment]
`git rebase`

**Comment by tvdijen** [comment]
I can't figure out how to do it.... git rebase doesn't show me those merge commits at all, so I can't squash them... Can you point me in the right direction here?

**Comment by thijskh** [comment]
The rebase will remove the merge commit by virtue of rebasing, there's no need to squash them explicitly. "Rebase" means to apply your own commits on top of a new "base" commit, being the top of the branch you're working against, so any merges will not be relevant anymore. Indeed with the rebase command you can also squash several regular commits together.

**Pull request closed without merging**
