### PR TITLE
Submit the logout response with the submit method. This fixes #555

### LINKED ISSUE #555: The LogoutResponse is not relayed to the IdP
The HTML form which should post the LogoutResponse to the IdP is not submitted when using the click event. This prevents the SLOService from completing the Logout process and the IdP complains that the Service Provider could not be logged out since it did not receive the LogoutResponse. This could be related to Issue #65.

### PR DESCRIPTION
**Pull request by rawroland**
Please do let me know if there are any conventions I missed.

### CODE REVIEW

**Comment by thijskh** [comment]
There is precedent for using `submit()` in other places in the code so I'm assuming this is indeed fine. But then you should remove the comment also in your commit. Otherwise it will get very confusing.

**Comment by thijskh** [comment]
On second thought, the change has been quite explicitly documented. https://github.com/simplesamlphp/simplesamlphp/commit/fee5bf7590ce02e2952aa812c18ddb772d98350d

@Christian-G, can you comment on what situation triggers this behaviour? And is it still relevant?

**Comment by jaimeperez** [comment]
Hi @rawroland!

Are you using master? Could it be that the problems you are experiencing with logout were due to the bug fixed in b23bb374bfcaaceb57ca979297604d6678acd9fc?

**Comment by rawroland** [comment]
@jaimeperez I am using master. No, I don't think that was my problem, because the sessions were correctly removed. The problem arose when sending the response to the IdP.

**Comment by tvdijen** [comment]
Hello Roland! Is this issue still present on version 1.15?

**Comment by thijskh** [comment]
Closing due to lack of information. Feel free to reopen when information is provided

**Pull request closed without merging**
