### PR TITLE
Remove undocumented feature of Extension with 'tags' attribute

### PR DESCRIPTION
**Pull request by tvdijen**
Nobody seems to have active memory of this functionality introduced 12 yrs ago, which has been undocumented ever since.

It was introduced here;
https://github.com/simplesamlphp/simplesamlphp/commit/1c37632ecd98983cf52386376777edfbea88acb7

@andreassolberg I don't expect your memory to go back this far, but do you have any memory of this feature at all?

### CODE REVIEW

**Review by thijskh — APPROVED** [review]
I cannot find out what this was intended to do. I am fine with removing it, but would be great if we could hear from Andreas if he recollects anything.

**Comment by tvdijen** [comment]
@andreassolberg Any recollection on this at all?

**Comment by thijskh** [comment]
Let's just merge this...

**Comment by tvdijen** [comment]
Agreed!

**Pull request merged**
