### PR TITLE
Set trusted.url.domains default to array()

### PR DESCRIPTION
**Pull request by dialogik**
See #265.

### CODE REVIEW

**Comment by jaimeperez** [comment]
Thanks a lot for this @dialogik!

Just one thing. Since this change could break some current installations, would you mind to add a note to the upgrade notes telling about this change and what SimpleSAMLphp users would need to do if they rely on redirections to third-party sites?

Thanks again!

**Comment by thijskh** [comment]
This changes the default in the template config (a good start). But I think we'd also want to change the code in Utils\HTTP to the different default, so that if someone does not have the setting in their config at all, they will get the 'secure' behaviour?

**Comment by jaimeperez** [comment]
That's probably the best approach. In that case it's even more important to update the upgrade notes, as well as the comment in the config template, warning about this option being enforced if not specified.

**Comment by dialogik** [comment]
The added the information to the [docs/simplesamlphp-upgrade-notes-1.14.txt](https://github.com/dialogik/simplesamlphp/blob/e5daae771ffdd780aa2285276232c41e8587eba1/docs/simplesamlphp-upgrade-notes-1.14.txt).

The `config.php` template – imho – doesn't need to be adapted as all required information are already contained (`null`, empty `array()` and an example `array()` with third party sites).

I'll take a look at `Utils/HTTP.php` later (maybe not until the weekend).

**Comment by jaimeperez** [comment]
I've just merged this PR and modified `SimpleSAML_Utils_HTTP::checkURLAllowed()` to change the default behaviour to forbid all redirections that are not to a trusted site.

**Comment by dialogik** [comment]
Thanks for accomplishing, didn't have the time.

**Pull request merged**
