### PR TITLE
properly calculate supported protocols based on config

### PR DESCRIPTION
**Pull request by restena-sw**
replaces unconditional claim for SAML1 and 2 support
this is a branch-1.14 backport of PR #310 as discussed in that PR's chat

### CODE REVIEW

**Comment by thijskh** [comment]
Thanks. I'm not sure it's currently a priority merge this in a future 1.14 release though.

**Comment by tvdijen** [comment]
I think it's fine to merge this by now, right @thijskh ?

**Comment by thijskh** [comment]
I'll merge it, but there are no guarantees that there will be future 1.14.x releases.

**Comment by tvdijen** [comment]
Oh right, I think I've missed the clue there...
Do we need something similar for 1.15?

**Comment by restena-sw** [comment]
A very long time ago my original PR was for master. It sure doesn't make much sense to do this only for 1.14. Maybe this can be merged into 1.15 and master?

**Comment by thijskh** [comment]
Yes

**Pull request merged**
