### PR TITLE
Add ETag and check for modifiedness of metadata

### PR DESCRIPTION
**Pull request by thijskh**
This is basically what you added fixed for 1.19 in #1672, #1673 also implemented for the new code in 2.0

### CODE REVIEW

**Review by tvdijen — APPROVED** [review]

**Comment by thijskh** [comment]
@tvdijen Do you see what I'm missing with the testcases? The problem is that the IdP metadata controller tests cannot find any saml2-idp-hosted metadata which they obviously need to generate some metadata. I can't seem to find out how to convince the testcase to find this metadata to be able to call the controller.

**Comment by tvdijen** [comment]
Wasn't the key for entityid like `entityId` or `entityID` instead of fully lowercase?

**Comment by thijskh** [comment]
I suspect that the issue is in that the configuration that speifies to use this metadata source for this test is not being used in some way or the other.

**Comment by tvdijen** [comment]
The underlying hidden exception is;
Exception: Could not find any default metadata entities in set [saml20-idp-hosted] for host [localhost : localhost/simplesaml]

I've tried to change the unit test to a `ClearStateTestCase`, but that didn't help..

**Comment by tvdijen** [comment]
It's really strange, as if somewhere along the line the config is reset... If I copy the configuration + metadata code from setup() into the failing tests, everything passes

**Comment by thijskh** [comment]
Locally if I run phpunit on just the file everything passes. If I run it on the tests/module/saml/srcController/ directory, it fails. So it seems it's relevant whether some other tests have already done something with Configuration...

**Comment by tvdijen** [comment]
This is curious, because it fails for me if I run the one file locally...

**Comment by thijskh** [comment]
At least I can also reproduce that part now

**Pull request merged**
