### PR TITLE
Log requesterid instead of entityid for stats

### PR DESCRIPTION
**Pull request by tvdijen**
When it comes to statistics, I'd like to now the number of logins per originating SP, instead of per SP-proxy...

### CODE REVIEW

**Comment by tvdijen** [comment]
@ghalse could you have a look and see if this doesn't conflict with your recent changes to the file?

**Comment by tvdijen** [comment]
Excellent, thanks very much!

**Comment by thijskh** [comment]
Do you want to know only that? So when there's at least one requesterid, you do not known which proxy was used. Or if there was more than 1 requesterid.

Would it make sense to keep logging our 'direct' peer (Destinaton) in the current place, but add also the list of requesterid's to that logline when available?

**Comment by tvdijen** [comment]
That would probably be the best way, but I'm worried that it implies a shitload of work on the statistics-module. At the very least, such change would invalidate any old stats...

**Comment by thijskh** [comment]
I think one way to be able to merge this is make it a configurartion of the authproc which defaults to the current behaviour?

**Comment by tvdijen** [comment]
I'll just close it.. It's been such a long time since I created it

**Pull request closed without merging**
