### PR TITLE
Update logoutstore table migration syntax for PostgreSQL

### LINKED ISSUE #891: Logoutstore migration is not compatible with PostgreSQL
sspmod_saml_SP_LogoutStore->createLogoutTable will attempt to change the column length of _authSource using the MODIFY syntax. This is not compatible with PostgreSQL.

### PR DESCRIPTION
**Pull request by akinspe**
Fixes #891

### CODE REVIEW

**Comment by thijskh** [comment]
Is it necessary to make a switch statement, can't it be one SQL query that is more generally accepted?

**Comment by akinspe** [comment]
Unfortunately I am not aware of a common DDL syntax that is valid in all supported drivers. This is one area of SQL that is not universal.

**Comment by thijskh** [comment]
Thanks. I've ported it to 1.16 and master aswell (could not merge/cherry-pick it automatically because files have changed completely re formatting in the meantime).

**Comment by akinspe** [comment]
Thanks! I look forward to the release of 1.15.5

**Comment by thijskh** [comment]
I am not sure that that will happen, I rather expect 1.16 to be released soon.

**Pull request merged**
