### PR TITLE
Add documentation to sp-remote for signature.certificate

### PR DESCRIPTION
**Pull request by dtsosie**
Adds documentation on behavior of signature.certificate when signature.privatekey is specified for a service provider.

### CODE REVIEW

**Comment by jaimeperez** [comment]
Hi @dtsosie!

I might be missing something, but I don't think such an option exists on SimpleSAMLphp...

**Comment by dtsosie** [comment]
modules/saml/lib/Message.php function addSign has this effect if the spMeta has signature.privatekey set. Finally got a service provider that cared if KeyInfo was returned and noticed this setting wasn't in spremote docs.

**Comment by jaimeperez** [comment]
Oh, I see... It's a bit strange that this option has been there undocumented up until now. Before merging, I'm going to check why and see if we should evaluate the existence of that option, so that maybe we don't even need to document it.

Of course, if you are using it and find it useful, feedback is welcome :+1:

**Comment by dtsosie** [comment]
Signature.privatekey Has its best purpose for staged idp key rollover.I use ssp as an idp for many mission critical systems that can't go down. Ssp didn't allow per service provider key changes prior. This setting allows a scheduling and phasing to occur per sp to minimize simultaneous disruption . Granted privatekey use, certificate is needed to compliment it for when x509 key info is required.

**Comment by jaimeperez** [comment]
Ah, that's true, now I recall! Yep, I agree, this should be properly documented :+1:

**Pull request merged**
