### PR TITLE
allow phpstan/extension-installer

### PR DESCRIPTION
**Pull request by monkeyiq**
Hopefully this will get the CI system happy again.

### CODE REVIEW

**Comment by monkeyiq** [comment]
I think the phpstan/extension-installer is being pulled in at this line...

https://github.com/simplesamlphp/simplesamlphp/blob/7cb00541c9ed925bbfe4b86fef48334ef60c7b00/.github/workflows/php.yml#L142

**Comment by monkeyiq** [comment]
It seems to be from simplesamlphp-test-framework-1.7.9 / require / phpstan/extension-installer

**Comment by tvdijen** [comment]
Yes, this needs to happen for all of our modules too.
I added the phpstan mockery-extension so it knows what to do with mocked objects

**Comment by monkeyiq** [comment]
It seems 2.2 and master are using an older version of simplesamlphp/simplesamlphp-test-framework in their composer.json. Maybe I should cherry pick this into master tomorrow so it is ready when the test framework is updated.

**Comment by tvdijen** [comment]
Yes, only master should be fine

**Comment by monkeyiq** [comment]
seems already picked

**Pull request merged**
