### PR TITLE
Feature/proxy auth

### PR DESCRIPTION
**Pull request by restena-sw**
As directed by Jaime, here's a separate pull request for Proxy Basic Authorization. 

The config option now defaults to "false" instead of "null" as in the previous PR.

There is also some documentation in the "Advanced Topics" now.

### CODE REVIEW

**Comment by jaimeperez** [comment]
Thanks Stefan!

Can you check this out?

`Parse error: syntax error, unexpected ')' in /home/travis/build/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php on line 370`

Looks like an extra `)` in the `if` statement.

**Comment by restena-sw** [comment]
Hi,

oops, fixed.

Am 15.01.2016 um 15:27 schrieb Jaime Pérez Crespo:
> Thanks Stefan!
> 
> Can you check this out?
> 
> |Parse error: syntax error, unexpected ')' in
> /home/travis/build/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php
> on line 370|
> 
> Looks like an extra |)| in the |if| statement.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simplesamlphp/simplesamlphp/pull/309#issuecomment-171974510>.
> 


-- 
Stefan WINTER
Ingenieur de Recherche
Fondation RESTENA - Réseau Téléinformatique de l'Education Nationale et
de la Recherche
2, avenue de l'Université
L-4365 Esch-sur-Alzette

Tel: +352 424409 1
Fax: +352 422473

PGP key updated to 4096 Bit RSA - I will encrypt all mails if the
recipient's key is known to me

http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xC0DE6A358A39DC66

**Comment by jaimeperez** [comment]
Great! Merged!

**Comment by tvdijen** [comment]
In HTTP.php, the line *$proxy_auth = $config->getString('proxy.auth', false);* should probably go inside the if-statement.
We shouldn't collect the value in case there is at all no proxy set.

**Comment by jaimeperez** [comment]
That's a good point, thanks @tvdijen!

Can you provide a fix for it?

**Comment by restena-sw** [comment]
Hi,

> Can you provide a fix for it?


Who is "you" now, any? My PR has already been merged, I don't think I
can easily modify things any more?

Stefan

-- 
Stefan WINTER
Ingenieur de Recherche
Fondation RESTENA - Réseau Téléinformatique de l'Education Nationale et
de la Recherche
2, avenue de l'Université
L-4365 Esch-sur-Alzette

Tel: +352 424409 1
Fax: +352 422473

PGP key updated to 4096 Bit RSA - I will encrypt all mails if the
recipient's key is known to me

http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xC0DE6A358A39DC66

**Comment by jaimeperez** [comment]
Ah, no, I don't think you can modify the PR now Stefan, I was asking Tim in this case, but of course if anyone is so kind to submit a new PR for that I'll be grateful regardless of who it was :smile:

**Comment by tvdijen** [comment]
I will, but obviously I'm in a really important meeting right now ;-).
*waves to other side of table*

Op dinsdag 19 januari 2016 heeft Jaime Pérez Crespo <
notifications@github.com> het volgende geschreven:

**Comment by tvdijen** [comment]
See #316

**Comment by restena-sw** [comment]
It's more like: see the last comment of https://github.com/simplesamlphp/simplesamlphp/pull/308 which I had to close due to code hygiene.

**Comment by restena-sw** [comment]
never mind, I meant to write about the other (metadata) PR. Too early.

**Pull request merged**
