### PR TITLE
- Added search.filter to allow for custom LDAP search filters

### PR DESCRIPTION
**Pull request by randomfire**
feature enhancement for Issue #25 
Added ability to define custom LDAP search filters
Based off rastrano's work https://groups.google.com/forum/#!topic/simplesamlphp/MjkxXM-0ru4

### CODE REVIEW

**Comment by thijskh** [comment]
Looks good! Only thing I'm missing is an update to the documentation for this new option.

**Comment by jaimeperez** [comment]
Thanks @randomfire!

I agree with Thijs, we should document this to avoid having undocumented configuration options.

**Comment by randomfire** [comment]
Agreed!  Still new to simplesamlphp, but where exactly did you need me to update?

**Comment by thijskh** [comment]
`modules/ldap/docs/ldap.txt` would be the place.

**Comment by randomfire** [comment]
Thanks.  Added documentation.

**Comment by jaimeperez** [comment]
Thanks a lot @randomfire!

**Comment by randomfire** [comment]
@jaimeperez @thijskh Thank you guys for working on such a useful product.  Glad I was able to contribute!

**Pull request merged**
