### PR TITLE
Janrain Authentication Module for SimpleSAMLphp

### PR DESCRIPTION
**Pull request by pbjanrain**
This module was designed to allow the Janrain Registration Widget to be used with Salesforce.com's SAML based Single Sign On.  This module has only been tested with standard Salesforce.com and Salesforce Communities user accounts.

This module should provide the necessary framework to allow the Janrain Registration platform to be used as a SAML IdP:

http://developers.janrain.com/overview/registration/registration-overview/

This module utilizes the Janrain Registration Javascript based Solution for Websites:

http://developers.janrain.com/overview/registration/registration-overview/javascript-based-solution-for-websites/

In order to successfully integrate the Javascript Solution you will need to have a properly provisioned Janrain Registration system.  If you are intending to utilize this module with Saleforce.com and the Salesforce.com Just-In-Time (JIT) provisioning features of their Single Sign-On (SAML) interface then you MUST make sure that the required JIT fields are configured as required fields in the Janrain Registration system otherwise null/empty values will prevent the JIT provisioning from being successful.

### CODE REVIEW

**Comment by jaimeperez** [comment]
Hi @pbjanrain!

Any news on this? Did you ever get your module to be installable with composer? If so, just tell me so that I can add it to the list of modules 😉

**Comment by pbjanrain** [comment]
Hi Jaime,

Unfortunately, it kind of fell of my radar with the constant onslaught of
new work.  I should probably resurrect that project and get it published.

It did make it all the way to production at:
https://rewards.wholefoodsmarket.com/

It worked out very well and enabled a fairly seamless integration between
our Janrain Registration and Salesforce Communities.  It is also in use
with their rewards mobile application.

Thanks,

Paul

On Fri, May 27, 2016 at 1:39 AM, Jaime Pérez Crespo <
notifications@github.com> wrote:

> Hi @pbjanrain <https://github.com/pbjanrain>!
>
> Any news on this? Did you ever get your module to be installable with
> composer? If so, just tell me so that I can add it to the list of modules
> 😉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/simplesamlphp/simplesamlphp/pull/111#issuecomment-222092188>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEmRb3XdsedDd49kyp-tJSvC2NkdM4dEks5qFq2ngaJpZM4CmTyw>
> .
>



-- 
*Paul Baker*, Software Developer && Solutions Architect, Janrain, Inc.
<http://bit.ly/cKKudR>
E: paulbaker@janrain.com| W: 503-488-6754 x298
Follow Janrain: Facebook <http://bit.ly/9CGHdf> | Twitter
<http://bit.ly/9umxlK> | YouTube <http://bit.ly/N0OiBT> | LinkedIn
<http://bit.ly/a7WZMC> | Blog <http://bit.ly/OI2uOR>

**Comment by jaimeperez** [comment]
Sounds like it would be a nice addition to the list, and probably useful for other people too. Should we then wait for it? 😄

**Comment by pbjanrain** [comment]
Hi Jaime,

I wouldn't hold my breath if I were you.  I'm in the middle of updating a
big Akka Scala mess that I inherited so it may be a while before I get any
"free" time (haven't had that for a few months).  I did bump this back up
my list though so hopefully I get to it sooner rather than later.

Thanks again,

Paul

On Fri, May 27, 2016 at 5:42 AM, Jaime Pérez Crespo <
notifications@github.com> wrote:

> Sounds like it would be a nice addition to the list, and probably useful
> for other people too. Should we then wait for it? 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/simplesamlphp/simplesamlphp/pull/111#issuecomment-222136477>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEmRb4e9LtLXSylUSZ-NhjDYTvGoZp0aks5qFubAgaJpZM4CmTyw>
> .
>



-- 
*Paul Baker*, Software Developer && Solutions Architect, Janrain, Inc.
<http://bit.ly/cKKudR>
E: paulbaker@janrain.com| W: 503-488-6754 x298
Follow Janrain: Facebook <http://bit.ly/9CGHdf> | Twitter
<http://bit.ly/9umxlK> | YouTube <http://bit.ly/N0OiBT> | LinkedIn
<http://bit.ly/a7WZMC> | Blog <http://bit.ly/OI2uOR>

**Comment by jaimeperez** [comment]
No problem at all Paul, don't worry. Just wanted to know if I should keep the issue open or not, so that I remember about this and can ping you like I did today.

**Comment by thijskh** [comment]
@pbjanrain Did you get around to this? Making a module installable with composer is quite straightforward.

https://github.com/simplesamlphp/composer-module-installer

I'm closing this issue here because it's not an actionable item in SimpleSAMLphp itself.

**Pull request closed without merging**
