### PR TITLE
Sort attribute values for consent

### PR DESCRIPTION
**Pull request by moffe42**
Fixes simplesamlphp/simplesamlphp#39

This ensures that the attribute hash is the same if the order of the attribute values changes. A user
givers consent to the values, not the order.

### CODE REVIEW

**Comment by thijskh** [comment]
Makes sense, thanks! Also great that you added a test straight away.

**Comment by jaimeperez** [comment]
Hi @moffe42!

This is an issue that we've had around for quite some time. It's not only the order of the values that's irrelevant, but also the order of the attributes themselves, which could also change.

Unfortunately, a change like this would break completely all given consent, so the change needs to be applied a bit more consciously. Probably the way to go is to look for consent w/o sorting, and if found, delete the old consent, sort both values and attributes, and save the new consent.

**Comment by thijskh** [comment]
@jaimeperez The attributes themselves are already sorted, right?

**Comment by jaimeperez** [comment]
It could be that that was fixed some time ago, I honestly haven't checked. If so, my apologies. I just remember that the attribute order was also an issue, and I don't have any memories of fixing that with all the hassle that would entail...

**Comment by jaimeperez** [comment]
Uhm, I think I might be mixing up things here, as from a quick look to the PR it's pretty obvious the attributes are sorted. I'll try to find out what's the issue I was thinking of then...

**Comment by moffe42** [comment]
As far as I remember from way back at my days at WAYT, it was only the order of the values that was an issue.

**Comment by moffe42** [comment]
Safe to merge??

**Comment by mschwager** [comment]
It may be out of scope of this change, but I'd say it's worthwhile to add another test that ensures the keys are sorted as well. If we're depending on that functionality, then we should test it :)

**Comment by moffe42** [comment]
Added test for attribute ordering.

**Comment by moffe42** [comment]
According to Travis CI the build is okay. It seems that the build status was not updated for some reason.

**Comment by moffe42** [comment]
Is this issue going to be fixed (pull request merge into master)? If not, then I will close this pull request.

**Comment by jaimeperez** [comment]
Merged! Thanks @moffe42!

**Pull request merged**
