### PR TITLE
Add IdP support for ECP profile

### PR DESCRIPTION
**Pull request by JohnMaguire**
This is my attempt to fix, clean up, and complete #233.

This has been tested against Exchange Online. It is missing a `composer.lock` update for the simplesamlphp/saml2#96.

### CODE REVIEW

**Comment by JohnMaguire** [comment]
One feature this lacks, that was mentioned in #233 as required, is sending a SOAP fault in the event of an error -- I'm not familiar enough with the architecture of simplesamlphp to make a call on the best method of doing this. If a maintainer could offer a suggestion, I'd appreciate it.

**Comment by JohnMaguire** [comment]
A failure to authenticate appears as such:

```
<?xml version="1.0" encoding="utf-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header><ecp:Response xmlns:ecp="urn:oasis:names:tc:SAML:2.0:profiles:SSO:ecp" SOAP-ENV:mustUnderstand="1" SOAP-ENV:actor="http://schemas.xmlsoap.org/soap/actor/next" AssertionConsumerServiceURL="https://login.microsoftonline.com/login.srf"/></SOAP-ENV:Header>
    <SOAP-ENV:Body><samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_97e0852bef04a40990a44815c26cdbb602a1f570a7" Version="2.0" IssueInstant="2017-06-01T17:34:05Z" Destination="https://login.microsoftonline.com/login.srf" InResponseTo="_a7041775-ca1b-4c9c-ae10-890426837a71"><saml:Issuer>https://localhost/dag/saml2/idp/metadata.php</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/><samlp:StatusMessage>SimpleSAML_Error_Error: WRONGUSERPASS</samlp:StatusMessage></samlp:Status></samlp:Response></SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

However, errors in XML parsing and such seem to result in HTML errors. (Maybe that's ok?)

Additionally, if ECP is not enabled, the binding won't be found, and of course we'll display an HTML error. (That seems correct, since ECP is disabled.)

**Comment by jaimeperez** [comment]
Thanks a lot for this @JohnMaguire!

As you can imagine, this is a significant amount of work, and it'll take time to review and discuss it properly. I'll get back to you as soon as I can.

**Comment by JohnMaguire** [comment]
Absolutely. :) It took a significant amount of work to figure out the first
time around, and I expect you'll have questions while reviewing. Please
feel free to ask for any clarifications you might need and I'll do my best
to respond in a timely manner. :)

**Comment by thijskh** [comment]
Great work on making progress on this issue. From reading the code I think this is something that should be mergable. On the `saml2`-side I see no blockers.

The main discussion point in the previous PR seems whether it's OK to only support basic authentication. I believe it is. We know concrete use cases that require basic authentication, and they are not usable with simpleSAMLphp right now. Merging this would improve the situation for those use cases; even if it would not support (theoretical?) certificate based use cases. I'm fine with implementing support for more methods if someone that actually needs that support steps up to it.

The documentation should of course be clear on what is supported and what not (yet). Maybe there's a little room for improvement there.

I don't have an ECP test setup myself; but do trust @JohnMaguire's efforts in that area. An independent confirmation that it works as intended in another environment would of course be ideal.

**Comment by JohnMaguire** [comment]
Thanks. I can update the documentation txt files with limitations shortly. I don't have this written up as a test, but the way I have tested this (aside from with actual production Microsoft Office 365 environments & Mozilla Thunderbird / iOS Mail) is [with this Postman request](https://gist.github.com/JohnMaguire/27319662fed6105ef175419e54325858), which simulates an AuthnRequest from an ECP client. We do have this working with a few Office 365 instances in production.

**Comment by JohnMaguire** [comment]
I have updated the documentation to define the limitations of ECP support. Having not worked with Holder of Key before, it's unclear to me if this feature is inherently supported due to support existing previously in simplesamlphp. There are two forms of ["Holder of Key" Subject Confirmation](http://docs.oasis-open.org/security/saml/Post2.0/saml-ecp/v2.0/cs01/saml-ecp-v2.0-cs01.html#_Toc366664728) listed in the SAML ECP spec. They are TLS Client Authentication, which I am nearly certain is unsupported, and "An enveloped XML Signature over the entire SOAP message."

If code for this second form of HoK has already been added elsewhere in simplesamlphp, this may actually be supported in the ECP profile as well. Since I do not have a test environment, I thought it better to simply list it as unsupported. If you have any guidance on how to test this, I would be happy to do so.

Thanks!

**Comment by thijskh** [comment]
Thanks a lot1 I think it's fine to merge. I'm holding off because we're now in the RC phase for 1.15 so in my view merging this could happen shortly after 1.15 is released.

**Comment by JohnMaguire** [comment]
Great working getting 1.15 out! Just wanted to bump this with a friendly reminder about this going into 1.16, before the codebase diverges too far to make this difficult. :smile:

**Comment by thijskh** [comment]
This is definitely on my radar!

**Comment by I-am-Gabi** [comment]
Hello! There are SP support for ECP profile?

**Comment by thijskh** [comment]
Sorry, this PR is about IdP support. As far as I know there does not exist SP support in simpleSAMLphp yet.

**Pull request merged**
