### PR TITLE
Adding support for SQLSRV driver to SQL.php

### PR DESCRIPTION
**Pull request by tashbaugh**
Issue #141 Create kvstore _expire column as a datetime data type when using the sqlsrv driver. Added case 23000 for insert and update statements for kvstore table when using the sqlsrv driver. Once these changes were made in my install of simplesamlphp I was able to successfully use a SQL Server 2008 database as my store for session data.

### CODE REVIEW

**Comment by thijskh** [comment]
Thanks. Can you perhaps clarify why you need to ignore that error even after you've changed the column type? Why does that error occur?

**Comment by tashbaugh** [comment]
After I changed the column type, I continually encountered the following error:

simplesamlphp[25152]
4 [29783bcf35] PDOException: SQLSTATE[23000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Violation of PRIMARY KEY constraint 'PK__SAML_kvs__63DAC062505BE5AD'. Cannot insert duplicate key in object 'dbo.SAML_kvstore'. The duplicate key value is (69bca63ac3f3eb24d3929d125e2a5528, session).

Once I added the switch case for error code 23000 then the above error no longer occurred and I was able to use SimpleSAMLPHP with SQL Server for session management.

Additionally, I found another problem on logout with data type of TIMESTAMP when it needed to be DATETIME for SQL Server. I will be making a separate PR for that one.

**Comment by dustinmoris** [comment]
Hi, thanks to your pull request I have submitted a very similar change, but instead of catching an exception and trying to update the row I used the MS SQL server MERGE command which is the equivalent of the MySQL REPLACE INTO command.

My change can be found here:

**Comment by thijskh** [comment]
I don't think we'll be merging this in this form.  #238 can be a starting point for anyone wanting to fix this issue (and has access to an actual MS SQL server).

**Pull request closed without merging**
