### PR TITLE
Docs: fix typo's

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by jaimeperez** [comment]
Thanks @tvdijen! I added you to the list of collaborators with write access, so it's not necessary any longer for you to submit PR's to fix stuff like this 😉

**Comment by tvdijen** [comment]
Maybe I'm doing it wrong then... Can commit directly to the master branch

**Comment by jaimeperez** [comment]
It's ok to open PRs if you are in doubt and want to discuss before merging, but otherwise, simple fixes like this are totally ok if you just commit them to master 😄 

Let me know if you have trouble with that, I think everything should be configured correctly, but I might have made a mistake...

**Comment by tvdijen** [comment]
afbeelding

**Comment by tvdijen** [comment]
Perhaps we can figure this out at next month's hackathon

**Comment by jaimeperez** [comment]
It might be that you need to be more than a collaborator. Check your email 😉

**Comment by tvdijen** [comment]
Unfortunately, that didn't make a difference..

**Comment by tvdijen** [comment]
I think this is my problem:
>Can't be edited or have files uploaded to it from the web

**Comment by jaimeperez** [comment]
I think I found the issue. Should be ok now...

**Pull request merged**
