### PR TITLE
Adresses issue #268 and makes the negotiate module a bit more configu…

### PR DESCRIPTION
**Pull request by tvdijen**
…rable, like you would configure ldap

### CODE REVIEW

**Comment by tvdijen** [comment]
It would probably be even better if the negotiate-module would use the ldap-settings from the ldap-module, but that would require more changes... I'll leave that decision up to the developers..

**Comment by thijskh** [comment]
Hi Tim,
Thanks for your work. But a first comment is that you appear to have changed all the newlines in the file. This leads to the diff becoming huge while in fact just a few lines have been changed. Can you push the commit again with the whitespace changes undone?

**Comment by tvdijen** [comment]
I tried, used different text-editors, but it keeps doing that... It looks like git is messing it up

**Comment by thijskh** [comment]
Maybe these links are helpful:
http://wiki.secondlife.com/wiki/How_to_avoid_DOS_line_endings_in_Windows_tools
http://stackoverflow.com/questions/8195839/choose-newline-character-in-notepad

**Comment by tvdijen** [comment]
I've tried it all, it's not working.. Different platforms, different editors..

**Comment by tvdijen** [comment]
I've managed to fix it using the online editor.. Did a new pull request

**Comment by thijskh** [comment]
Thanks, diff is much clearer now (in #270)!

**Pull request closed without merging**
