### PR TITLE
Avoid data collision in memcache and PSR-2 reformatting

### PR DESCRIPTION
**Pull request by tvdijen**
This is an update to Memcache.php to prevent data collision when running multiple instances of SSP on one host and more than one of them is configured to use memcache.
It introduces a new setting in config.php that allows you to come up with a unique prefix per instance.
Also PSR-2 reformatting of the Memcache.php file is done.

### CODE REVIEW

**Comment by thijskh** [comment]
Much better, thanks :-)

I've rebased it to remove the 2 merge commits and squashed the config one, but that's more a matter of taste I guess.

**Comment by tvdijen** [comment]
You're welcome... But, I've made a really stupid mistake.. The code is referencing the wrong property in the config file, because I was in doubt whether I should call it 'name' or 'prefix'... Does that require a new PR? I've fixed it in my fork...

**Comment by thijskh** [comment]
I don't see the fix in your fork?

**Comment by tvdijen** [comment]
https://github.com/tvdijen/simplesamlphp/commit/a9cdecf5fb01638ba8390aa3e99bc04c62138a99

**Comment by thijskh** [comment]
I've merged that diff now. Thanks again for your work!

**Pull request closed without merging**
