### PR TITLE
Backport Twig2 support

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by tvdijen** [comment]
That's why I've been asking for feedback [here](https://github.com/simplesamlphp/simplesamlphp/issues/753), but like you said yourself on the discussion board, usually the only way to get feedback us to just release it

**Comment by thijskh** [comment]
Alright but is this not somethink that should only be part of an upgrade 1.16 to 1.17, not of an upgrade from 1.16.2 to 1.16.3?

**Comment by thijskh** [comment]
I understand that you tested it, but what about people’s own websites and modules? They are prepared for some breakage potential with a new 1.17 but I think not with an upgrade from 1.16.2 to 1.16.3

**Comment by tvdijen** [comment]
I agree, I think we should have a 1.17 release.. Lot's of changes on master since 1.16 was released.
Jaime thought it was too soon for a 1.17 release and suggested backporting to 1.16 due to high demand of this feature, see discussion board...

**Comment by jaimeperez** [comment]
Hi guys!

As Tim said, I suggested backporting it as there's quite some people complaining about conflicts because they are already using Twig 2, so in that sense, I see this as a bugfix. However, it is also true that upgrading to a new major version of the library could cause unforeseen trouble, and I also have to admit I haven't tested really extensively.

So I'd say let's release this as part of 1.17, and use it as a way to encourage people to upgrade.

**Pull request closed without merging**
