### PR TITLE
Remove legacy routes

### PR DESCRIPTION
**Pull request by tvdijen**
Ticks box 3 on #1643 

TODO: Add nginx equivalents for the `mod_rewrite` rules

### CODE REVIEW

**Comment by thijskh** [comment]
I think we are breaking too much if we also want to impose these rewrite rules on users. This does not actually reduce complexity, it only moves it to a different point (and it takes all deployers effort to do that, and us to support them and to document it for various webservers etc).

The costs of keeping the files `www/` with just the bare content needed to make them work is simple and robust and I don't think this cost outweighs the added costs for solving it in a different point. Requiring too many changes in the end will mean that people stay longer on 1.19.

As an example, `www/admin/index.php` just contained this before it was removed.

```php
<?php

require_once('../_include.php');

$httpUtils = new \SimpleSAML\Utils\HTTP();
$httpUtils->redirectTrustedURL(\SimpleSAML\Module::getModuleURL('admin/'));
```

Other pages can simply call the relevant controller instead of performing a redirect but the amount of code is likely similarly in the order of less than a handful of lines.

**Comment by tvdijen** [comment]
You really want an extra redirect on all your SAML endpoints?

**Comment by jaimeperez** [comment]
Yes, we've been discussing this over the weekend and I fully agree with Tim. The whole point of 2.0 is precisely to be able to do backwards-compatibility breaking changes as the first new major in some 13-14 years. I completely see your point about breaking too much so that people refrains from updating, but at the same time I don't think it's a good idea to keep legacy forever just to avoid asking deployers to do something on their side. Consider also that for new deployments they won't care about these changes at all.

From a technical standing point there is no reason to keep multiple endpoints, in my opinion. Having a single entry point for all the endpoints means less code duplication and a single point to enforce anything that we need. It has been considered good practice for many years and I'd say most major frameworks do this. The alternative we had was simple, sure, but it was also problematic in the sense that it was enforcing an HTTP-redirect for each request, with the added roundtrip and consequential hit in performance for main endpoints.

The alternative (using `mod_rewrite`) is relatively common nowadays, I believe. The rules aren't that many and I think it's relatively simple to configure. The benefit is huge for us because it allows us to have, finally, a fresh start without legacy. If we'd rather keep the legacy scripts per endpoint, we won't have a chance to get rid of them and have a clean codebase until 3.0, which could of course happen next year (although I would argue it's worse to break bc in small changes more often than to break it more but on rare occasions), but more realistically will not happen in many years to come.

We've been putting a lot of effort on 2.0 for years and the original plan already went ashtray, but I believe in this moment, with a new maintainer hopefully in place soon, the timing is right to do this change. Just my two cents 😄

**Comment by thijskh** [comment]
I just don't see the argument why the rewrite approch is better than keeping small www files approach. It seems that they are similar in complexity and amount of legacy that we keep, but one requires people to change stuff while the other doesn't and just works out of the box.

**Comment by tvdijen** [comment]
I'm fine with the scripts, as long as we mark them `deprecated` and make sure the metadata generator provides us with the _new_ endpoints. This PR could be merged as soon as we branch off 2.0

**Pull request closed without merging**
