### PR TITLE
PSR2 / Whitespace

### LINKED ISSUE #458: PSR-2 compliant whitespace
Fix whitespace as per PSR-2.

When fixing whitespace, ONLY do that for that commit, as this makes `git blame -w` work better.
Reference this issue in the commit message, for instance in the body as "For: #458". Don't do too many files in one go, only one module per commit for instance.

If fixing whitespace in a template leads to it rendering differently, the template is bugged. Take screenshots of before and after, add them to a new issue referencing this one, and also mention what browser you are using.

### PR DESCRIPTION
**Pull request by tvdijen**
- Fixes a couple of whitespace issues
- Namespaced tests

Closes #458

There are some issues left that need refactoring, so another run should be done as part of a 2.0 release

### CODE REVIEW

**Comment by thijskh** [comment]
Only userpassorgbase fails with 5.4; probably not worth fixing because already decided 5.5 will be minimum for this release.

**Comment by tvdijen** [comment]
Yes, since the PR Jaime's is working on also relies on 5.5 I've decided to remove the legacy-code while at it

**Comment by thijskh** [comment]
I think a PHP version bump is good to commit explicitly. So I've committed this separately now. So if you rebase this PR I think we should be ok (and you could drop the special casing in userpassorgbase).

**Comment by tvdijen** [comment]
I'm not sure I follow.. What's there to rebase? And what special casing?

**Comment by thijskh** [comment]
Right, this was already fixed. So good to go!

**Comment by tvdijen** [comment]
P.S.: Should we bump the version on the SAML-library as well?

**Comment by thijskh** [comment]
Not necessarily I think since we're not currently changing anything there that makes it so

**Pull request merged**
