### PR TITLE
XML data is loaded using SAML2_DOMDocumentFactory class

### PR DESCRIPTION
**Pull request by sgomez**
Refactoriced the way than XML is loaded to use SAML2_DOMDocumentFactory class.

### CODE REVIEW

**Comment by thijskh** [comment]
I would be fine with merging this if the saml2 dependency is bumped to 1.7.0.

@jaimeperez?

**Comment by sgomez** [comment]
I'd like to propose to set the saml2 version constraints to ```"simplesamlphp/saml2": "~1.7"```. Thats mean from ```>= 1.7.0``` to ```<2.0.0```. With the current value, ```~1.5.3```, his updates are limited to ```<1.6.0```.

**Comment by thijskh** [comment]
Fine with me!

**Comment by jaimeperez** [comment]
Hi!

I've just merged this, sorry again for the time this took. That was an outstanding work, guys!

Dank, @thijskh and @DRvanR!

¡Muchas gracias Sergio!

**Pull request merged**
