### PR TITLE
Document IDPList option on saml20-idp-remote.php

### PR DESCRIPTION
**Pull request by pradtke**
Per https://groups.google.com/d/msg/simplesamlphp/ATKQksysR5s/3VhjdLbTAgAJ
there is a feature to allow IdPs to respond to requests sent to different
IdP entityIDs.

### CODE REVIEW

**Comment by tvdijen** [comment]
It is already documented here: https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-scoping.md

And I don't think it was designed to specify which IdP's may respond... I think it was meant for proxying IdP's to be able to adjust the WAYF

**Comment by pradtke** [comment]
@tvdijen I think scoping is a different feature, but unfortunately with the same parameter name.
The feature I'm referring to is from [these lines](https://github.com/simplesamlphp/simplesamlphp/blob/e85780ef9cc60a47a7d304642d4bb4b0d235d9a0/modules/saml/www/sp/saml2-acs.php#L99-L107), when a response comes back to the SP

```php
    if ($state['ExpectedIssuer'] !== $idp) {
        $idpMetadata = $source->getIdPMetadata($idp);
        $idplist = $idpMetadata->getArrayize('IDPList', array());
        if (!in_array($state['ExpectedIssuer'], $idplist, true)) {
            throw new SimpleSAML_Error_Exception(
                'The issuer of the response does not match to the identity provider we sent the request to.'
            );
        }
    }
```

which is different from scoping.

**Comment by tvdijen** [comment]
Okay... Is it even legit to receive a response from an entity other than the one you sent your request to? Other than in a idp-first scenario...

**Comment by pradtke** [comment]
¯\_(ツ)_/¯  I looked through some of the specs and I didn't see any mention that the issuer had to match the entityID that the original authNRequest was sent to.

I don't use the feature, and I don't know how other SP software (such as shib) behaves - I just thought it deserved documenting since (per my original link the the mailing list) some people use it. 
If we want to document it, I think I should at least adjust the text to mention that it is unrelated to scoping.

**Comment by trscavo** [comment]
Jumping in the middle here...

I don't understand the use case but any IdP can push a response to an SP at any time. (At the end of the day, that's all this is...an IdP-initiated response.) It's up to the SP to verify the signature and accept the response content.

**Comment by tvdijen** [comment]
I do understand it... I've heard it before:  "Why can't an IdP respond back to the requester right away, instead of following back the route through all those SAML-proxies??"
Architects see it as a way to reduce traffic...

But those intermediate proxies may handle MFA, attribute aggregation, attribute release, etc...  That's why my first response was:  is that even legal??

**Comment by thijskh** [comment]
I'm merging this since it correctly documents how SSP works. Discussion on whether it's OK to work this way could be had separately - but as long as it does work this way, it should be documented.

**Pull request merged**
