### PR TITLE
Use saml2 v2 and xmlseclibs v2

### PR DESCRIPTION
**Pull request by relaxnow**
Use the new PSR2 classes from simplesaml/saml2 and robrichards/xmlseclibs.

### CODE REVIEW

**Comment by DRvanR** [comment]
As discussed, `class_alias`es for all existing SAML2 classes should be added. They should be loaded always. Furthermore the autoloader should be expanded to check if classes are loaded the old way and trigger a deprectated notice (`trigger_error('some meaningful message', E_USER_DEPRECATED)`).

This provides users and module maintainers with a BC way to keep using SAML2 while allowing SSP to move forward and adopt SAML2 2.x, which in turn makes maintenance and development of SAML2 easier.

**Comment by jaimeperez** [comment]
Hi guys!

I've just added an autoloader to the SAML2 library, creating aliases on demand for all old-style class names. It also considers the case of the only class that has been renamed (`SAML2_Const`, for obvious reasons).

It does not log any warning yet, as I wanted to discuss that with you two. I'd consider `error_log()` out of the question, and `trigger_error()` might be a bit excessive if it ends up dumping stack traces to your logs, depending on your configuration. Are we logging anything in the SAML2 library, via the SSP compat layer? What would you suggest to use?

BTW, we should probably log warnings too for all the classes deprecated in SimpleSAMLphp that will disappear or be renamed in 2.0.

**Comment by DRvanR** [comment]
Cheers, much appreciated!

> trigger_error() might be a bit excessive if it ends up dumping stack traces to your logs, depending on your configuration

afaik warnings do not trigger the dumping of a strack trace but this would just be lines like:
`Deprecated: <message> in <path> on line <lineno>` which to me would be perfectly acceptable. Easy to grep and helps locate code to fix. 

Logging anything through the SSP compat layer doesn't seem to be a good option to me as this project is used outside of SSP as well.

Personally I'd opt for the `trigger_error($msg, E_USER_DEPRECATED)` - nice sideeffect would be that you could suppress the warnings if you'd want to :wink:

**Comment by jaimeperez** [comment]
I've seen the traces myself while using `trigger_error()`, that's why I was asking. The message logged is also a bit different than that, but I guess it could be the particular configuration in my development VM.

Let's proceed with `trigger_error()` in any case :+1:

**Comment by jaimeperez** [comment]
By the way, I submitted a PR to XMLSecLibs (robrichards/xmlseclibs#93) to provide the exact same functionality. Let's see if Rob accepts it, it would simplify things a lot.

**Comment by jaimeperez** [comment]
Hi all!

This was finally solved in c23722a47dc196428f9ab5d68fd25ad74a3c6cdf.

In the end, it was more complicated than expected, even though we had the class aliasing in the SAML2 library. Basically, since class aliases create new virtual classes, those classes lose all inheritance relationships, so it's no longer possible to test an object and see if it inherits from some abstract class or interface.

In any case, all the code in master is finally using the 2.x branch. Sorry that I couldn't merge your work directly, Boy!

**Pull request closed without merging**
