### PR TITLE
fix for: ‘autofill username’ that resulted in a WRONGUSERPASS

### PR DESCRIPTION
**Pull request by doedje**
The commit [autofill username when it's hinted by the SP in a request parameter](https://github.com/simplesamlphp/simplesamlphp/commit/2eaa634f095143f43d320e8b305378efd8d61431) resulted in a WRONGUSERPASS error when an SP (outlook.office.com for instance) also supplies a 'username' attribute in it's request.

The code from file `modules/core/src/Controller/Login.php` at the `private function handleLogin` would trigger the `handleLogin` functions of either `UserPassOrgBase` or `UserPassBase` without a `$password` being set. Changing the `if` statement to only check for `!empty($password)` fixes this.

I also moved up the `public function loginuserpassorg` so it is now together with the other `public function loginuserpass`. I also think the `private function handleLogin` could use a bit more cleaning up, which I am willing to do and add to this PR, but rather discuss these with some of you before I start... ;)

### CODE REVIEW

**Comment by tvdijen** [comment]
> "[..]" resulted in a WRONGUSERPASS error when an SP [..] also supplies a 'username' attribute in it's request

I'm not sure I follow.. What would a request look like?

**Comment by doedje** [comment]
As copied from SAML-tracer, this is the request sent to our SSP-IdP when trying to login at outlook.office.com with my mail address: (shortened SAMLRequest and RelayState for readability)
```
POST
SAMLRequest: PHNh...VzdD4=
RelayState: estsredirect=2&estsrequest=rQQIARAA...k2_CXp-Aw2
username: remy.blom@hku.nl
```
On our IdP I already implemented the change from this PR. So you will not get an error. But with the code in 2.2.2 it will try to login (using LDAP in our case) right away since $username is filled.

**Comment by tvdijen** [comment]
I'm worried now that an empty username and non-empty password will now throw an exception. Could you verify this?

**Comment by doedje** [comment]
It will show the WRONGUSERPASS error, which is quite as expected...

**Comment by tvdijen** [comment]
No, no, it shouldn't error.. It should just show the login-screen again.. That's what the `!empty($username)` did..

**Comment by doedje** [comment]
Sorry, I should be more precise. When I try to login with an empty username and non-empty password, it will show BOTH the "Incorrect username or password" WRONGUSERPASS error and the login form again.

**Comment by doedje** [comment]
okay, but maybe we should get down on what that function should do:

- only username, just show form
- only password, just show form
- both username and password, try to login
- only show WRONGUSERPASS when login failed.

right? because then I know what to aim for when rewriting that function.

**Comment by tvdijen** [comment]
Could it be that you're not using the latest version of the ldap-module? Because I cannot reproduce the issue (and the prefilling of the username isn't working either)

**Comment by tvdijen** [comment]
But then why does my setup not give the same issue you are facing? :/

**Comment by doedje** [comment]
Hmmm, if we only knew... I also tried disabling my theme, but the result is the same...

(surf to outlook.office.com, enter my mail address, this is what I get...)

image

**Comment by tvdijen** [comment]
I've reverted the autofill commit and took a different approach in 1139c8623

**Comment by tvdijen** [comment]
I'm closing this because the issue has been resolved. Please feel free to discuss the improvements to `handleLogin` here.

**Comment by doedje** [comment]
There is something with all the nested `if`s that is bothering me. I like to give it a shot to try and iron out the folds ;)

- only username, just show form
- only password, just show form
- both username and password, try to login
- only show WRONGUSERPASS when login failed.

This still stands right?

**Comment by tvdijen** [comment]
Yeah, it's messy.. Feel free to improve it!
Just bear in mind that this code is also used for the username/pass/org flow..


>
> * only username, just show form
> * only password, just show form

I don't think I agree. We cannot process the form unless both username and password are present.. If anyone tries to post it without username or password, it should show the "Wrong username or password" error.

**Pull request closed without merging**
