### PR TITLE
Flexible namespace

### PR DESCRIPTION
**Pull request by tvdijen**
It doesn't make much sense to have a hard coded AttributeNamespace used for every attribute...
It is a mandatory field in SAML1.1, so we keep the hard coded value as a fallback.

This will convert an attribute called http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress to:
<saml:Attribute AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" AttributeName="emailaddress">

### CODE REVIEW

**Comment by jaimeperez** [comment]
Thanks Tim!

Would it make sense to move this code to its own function somewhere (something like `getAttributeNamespace()` that takes an attribute name as input and returns a tuple with the namespace -with the current default when no namespace is part of the name- and the attribute name itself)? I'm thinking that by doing that, we can add tests for the function and ensure that everything works fine.

**Comment by tvdijen** [comment]
Sure, I can do that! But where would you put the function, because I don't think it should be a function of the ADFS-class then... Somewhere within the Utils namespace perhaps?

**Comment by jaimeperez** [comment]
That's a very good question indeed. Maybe `SimpleSAML\Utils\Attributes`? If the default is passed as a second parameter, it can then be reused elsewhere, and wouldn't be ADFS-specific...

**Comment by jaimeperez** [comment]
Thanks a lot Tim! 😄

**Comment by tvdijen** [comment]
Ohh, you were quick!  I was about to add a test for it.
Now I have no experience with writing tests... Would this cover it?
https://github.com/tvdijen/simplesamlphp/commit/d3a907670cd9d837fc7ba7b98f6c3dc8ac9f00a3

**Comment by jaimeperez** [comment]
Ops, sorry! Didn't know you were also working on a test, and I was too quick indeed.

Anyway, I made a test myself, and also changed the second parameter to be mandatory, so that the function is not ADFS-specific. Take a look at ec379ac30543c59e64e435c815435d6a2d692ead and tell me if you see anything wrong.

**Pull request merged**
