### PR TITLE
Update Negotiate.php

### PR DESCRIPTION
**Pull request by tvdijen**
This commit addresses Issue #268 and makes the negotiate module a bit more configurable, like the ldap-module it's leaning on..

### CODE REVIEW

**Comment by thijskh** [comment]
Hi Tim, thanks for your PR! Seems like a useful change. I'll merge it.

**Comment by tvdijen** [comment]
I see I've missed a few things...

-Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.

Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.

**Comment by thijskh** [comment]
Sorry, is this about the other PR?
In any case, merged is merged so we can then only merge additional changes (via a new PR).

**Comment by tvdijen** [comment]
Yeah, I messed up.. It's about #272 
I'll come up with a new PR when I've fixed a bunch of files to comply to the coding guidelines...

**Pull request merged**
