### PR TITLE
Bug/previous sessions

### PR DESCRIPTION
**Pull request by shuadoc**
Related issues:

https://github.com/simplesamlphp/simplesamlphp/pull/349
https://github.com/simplesamlphp/simplesamlphp/issues/365
https://github.com/simplesamlphp/simplesamlphp/pull/224

This extends the patch for those issues, saving the previous_session across multiple requests.

### CODE REVIEW

**Comment by jaimeperez** [comment]
Hi @shuadoc!

Could you please elaborate a bit on why is this necessary?

**Comment by shuadoc** [comment]
Of course,

This is needed to preserve the previous_session variable across multiple requests.  Currently previous_session is stored in an object which is destroyed at the end of a single request.  During the second request, previous_session is actually set to the current session.

This commit stores previous_session in the active session to be available for subsequent requests.

An example of when this is necessary:

 - User visits service provider
 - Service provider sets session variables
 - User redirected to identity provider
 - User logs in and is redirected back to service provider

Current behavior in detail:

 - User visits service provider
 - Service provider sets session variables
 - Simplesamlphp is loaded, changes session
 - Simplesamlphp redirects user to identity provider
 - (Request ends, SessionHandler and previous_session are destroyed, cannot call cleanup())
 - User returns from identity provider
 - Simplesamlphp is loaded, sesson stays the same
 - (At this point, the SessionHandler sets previous_session to be the same as the active session)
 - Simplesamlphp finishes execution, returns control to service provider 
 - Service provider calls cleanup(), session remains the same
 - Service provider continues without session variables from before

The only options I can see are:
 - Always have simplesamlphp handle our applications sessions, even for clients who aren't using saml
 - Store previous_session in the current session
 - Prevent simplesamlphp from altering active sessions

Thank you!
Josh

**Comment by jaimeperez** [comment]
Thanks for the detailed response Josh!

I think the problem here is due to the application relying on the `cleanup()` method to retrieve the session, while it should retrieve it normally, just as before the application was _domesticated_ to use SimpleSAMLphp. Let me make some comments on the alternatives you are suggesting:

> Always have simplesamlphp handle our applications sessions, even for clients who aren't using saml

You shouldn't mix both. All the changes in the last releases were intended precisely to keep both sessions (SimpleSAMLphp's and the application's) separated. That way you avoid any possible bugs in the application to mess SSP's session, and the other way around. Besides, there are no guarantees that SimpleSAMLphp will respect (today or in the future) whatever information you store on its session.

> Store previous_session in the current session

Maybe the name of the property is a bit misleading. It's not intended to keep track of a session existing before, as there's no relationship in time between both sessions (they are supposed to coexist). On the other hand, this new mechanism is intended to allow an application to keep its own session when using SimpleSAMLphp.

> Prevent simplesamlphp from altering active sessions

SimpleSAMLphp does not alter active sessions. That precisely why it closes the session before opening its own one, to avoid any alterations. Unfortunately, PHP's session handler does not allow to have two sessions open at the same time, and that's why we need to do this.

In any case, to summarize: if you are using PHP sessions both in your application and in SimpleSAMLphp, you need to make sure they use different cookies, and in your application you should do things exactly the same way as you were doing them before, with two exceptions:

1. If you weren't using named sessions, you will need to start doing it (`session_name()`).
2. You will also need to call the `cleanup()` method **after** calling SimpleSAMLphp.

So your application should be doing something like this:

```php
<?php

include('....../lib/_autoload.php');

$as = new SimpleSAML_Auth_Simple('default-sp');

session_start();

if ($_SESSION['is_valid']) {
    echo "We are already authenticated";
} else {
    $as->requireAuth();
    $s = SimpleSAML_Session::getSessionFromRequest();
    $s->cleanup();

    $_SESSION['is_valid'] = true;
}

// do whatever we need to do
```

I'm closing the PR for now. Feel free to comment if you think I'm missing something.

**Comment by shuadoc** [comment]
Thanks Jaime,

After setting 'session.phpsession.cookiename' to a value other than the default, this is working correctly without the above commit.

It would appear that PHP sessions work fine with the default session config, until including simplesamlphp with default session config.   All appears to be going well, until you need a specific edge case to work properly.  This seems undesirable IMHO.

Please rate the following options:

A) A logged warning when 'session_name' and 'session.phpsession.cookiename' are configured such that there will be a collision.

B) Instructions to set either session_name and/or session.phpsession.cookiename here: https://simplesamlphp.org/docs/1.14/simplesamlphp-maintenance#section_5

C) config-templates/config.php to contain instructions on why they might want to set session.phpsession.cookiename (and that if they set this configuration, they must also use the cleanup() function.)

D) Simplesamlphp to cleanup() after itself before exiting, or before returning control to calling application.  (If and only if the two session_names are different.)  (The cost of this one is higher than the benefit.  Still, it's often nice to clearly state what might happen in an ideal world.)

Regards,
Josh

**Comment by jaimeperez** [comment]
Thanks for the feedback @shuadoc, glad you got it working!

I wouldn't say this is a corner case. If your application is already using PHP sessions and you configure SimpleSAMLphp to use them too, you need at least one of them to **not** use the defaults.

In any case, regarding your suggestions:

A) is a very good idea, thanks!

B) should probably be mentioned [here](https://simplesamlphp.org/docs/1.14/simplesamlphp-maintenance#section_2) (the section on session configuration).

C) is the consequence of an unfortunate decision. There shouldn't be two different configuration options to set some properties of the session, depending on whether you are using PHP sessions or something else. What we should do is actually to get rid of the `session.phpsession.*` configuration options, IMHO. In any case, there is already [documentation talking about using the `cleanup()` method](https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6).

D) is impossible to do, unfortunately. The reason is that you can't know when the user is done using your API. Should we clean the session up when returning from `requireAuth()`? What if the app calls `getAttributes()` afterwards? If we do that, we would need to do it for each exposed API method, and that means loading and unloading sessions multiple times, with the overhead that implies. So I think the lesser evil here is to provide a method for the user to mark the end of the use of the API, so that the previous status is restored.

Thanks again for your suggestions, they are duly noted and will be addressed as soon as possible 😃

**Pull request closed without merging**
