### PR TITLE
Alter logics to support HTTP/2.0

### LINKED ISSUE #1537: HTTP 2.0 Infinite Redirects from HTTP 302 Response
An infinite redirect loop occurs on login with HTTP 2.0 enabled. 

In [lib/SimpleSAML/Utils/HTTP.php#redirect](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L233) there is a check for HTTP/1.1 that sets the header HTTP 303. With HTTP 2.0 enabled, the header HTTP 302 is set and an infinite redirect loop occurs on login. 

Is HTTP 2.0 unsupported? 
Any repercussions from patching a HTTP/2.0 check?

Configuration:
- simplesaml: 1.17.2
- PHP: 7.3.32
- nginx: 1.20.1

### PR DESCRIPTION
**Pull request by tvdijen**
Closes #1537

### CODE REVIEW

**Comment by thijskh** [comment]
I propose to instead simplify this a lot and set the code to be 303 always, unconditionally. We have no need to support theoretical Netscape Navigators or other ancient things. If they are still around they will not be able to connect to any reasonably secure TLS configuration. All the complexity we have now just leads to bugs.

**Comment by tvdijen** [comment]
Agreed on the 303, but the distinction between GET/POST is unclear to me and Jaime.. We should check it out

**Comment by thijskh** [comment]
No, the whole world seems to still use the legacy 302. Probably because there's nothing actually wrong with it in practice, only in theory.

**Comment by thijskh** [comment]
For what it's worth, mellon uses 303 since ages.

**Comment by tvdijen** [comment]
This should be it then... I hope we don't introduce any unwanted side-effects

**Review by thijskh — APPROVED** [review]
Yes, great. Just KISS please.

**Pull request merged**
