### PR TITLE
use session_create_id() to comply with session settings

### PR DESCRIPTION
**Pull request by aberenyi**
A possible solution for https://github.com/simplesamlphp/simplesamlphp/issues/566.

### CODE REVIEW

**Comment by mariendev** [comment]
Just a coding remark: you must write the function name as a string and not as an (undefined) constant:
Your code: function_exists(session_create_id)
Right version: function_exists("session_create_id")

**Comment by aberenyi** [comment]
@mariendev good catch, fixed

**Comment by jaimeperez** [comment]
Hi @aberenyi!

Thanks for your PR and sorry for the delay from my side.

I think this would be nice to have, but at the same time I'm a bit worried about people using bad defaults. Would it be possible to check somehow the parameters used by PHP (those configurable via `php.ini`) and at least log a warning if they are worse than what we have today?

**Comment by tvdijen** [comment]
How about this:

`    public function newSessionId()
    {
        // generate new (secure) session id
        if (function_exists('session_create_id')) {
            $sid_length = (int) ini_get('session.sid_length');
            $sid_bits_per_char = (int) ini_get('session.sid_bits_per_character');

            if (($sid_length * $sid_bits_per_char) < 128) {
                \SimpleSAML\Logger::warning("Unsafe defaults used for sessionId generation!");
            }
            $sessionId = session_create_id();
        } else {
            $sessionId = bin2hex(openssl_random_pseudo_bytes(16));
        }
        SimpleSAML_Session::createSession($sessionId);
        return $sessionId;
    }`

**Pull request closed without merging**
