### PR TITLE
locale: add support for transitioning st to en_LS

### PR DESCRIPTION
**Pull request by monkeyiq**
As reported here https://github.com/simplesamlphp/simplesamlphp/pull/2269 the `st` language code needs to be updated to the Symfony locale similar to how `pt-br` and ` zh-tw` have already been handled.

### CODE REVIEW

**Comment by tvdijen** [comment]
Great! Now the locales-directory has to be renamed (also for the modules).

**Comment by monkeyiq** [comment]
updated. Do you recall if other projects on ssp github needed updates in the locale as well before?

**Comment by tvdijen** [comment]
We would have to go over all the module-repos that have locales.. I haven't done this for pr_BR and zh_TW yet either.

**Review by tvdijen — APPROVED** [review]

**Comment by monkeyiq** [comment]
I created https://github.com/simplesamlphp/simplesamlphp/issues/2277 to track the updates to other projects and avoid the task getting stale/lost.

**Pull request merged**
