### PR TITLE
Https fixes

### PR DESCRIPTION
**Pull request by markwick09**
Looking to be able to configure the application url with more granularity.

### CODE REVIEW

**Comment by tvdijen** [comment]
Honestly, all I see here is added complexity without added functionality.. What's the benefit here?

**Comment by markwick09** [comment]
The specific use case is:
- One pool of web servers, behind an LB. HTTPS is terminated at the LB.
- Two different host names resolve to the same pool of servers.

Current configuration restricts that we can only override the whole URL, or nothing. The current means of detecting HTTPS traffic in the above scenario, leaving us no options.
The new config option allows overriding the protocol without necessarily overriding the host name. I'd certainly be open to implementation suggestions as alternatives to handle the above scenario.

**Comment by tvdijen** [comment]
Well, the configuration is a PHP-file, so you could render the baseurl setting dynamically by replacing the domain name with `<?= $_SERVER['SERVER_NAME'] ?>`

**Comment by tvdijen** [comment]
Hi @markwick09! I'm still curious about your use-case... Maybe you can elaborate on it a bit more!
Looking at what you're sketching right now, that's already possible, so I'm not sure what you're trying to accomplish...

I see you're having two nodes behind a load balancer that is terminating TLS and will forward request to the backend-nodes. In this case, your LB would host something like https://idp.example.org and that's exactly what you'd configure your backend nodes to when it comes to the `baseurlpath`... It doesn't matter if your nodes run on HTTP/80 in this case, SSP is smart enough to handle this... So what is it that SSP doesn't handle for your use-case?

**Comment by jaimeperez** [comment]
I agree with Tim. I think the particular use case that justified this PR in the first place can easily be covered with the current configuration option by using variables and PHP code to build the actual value in `baseurlpath`. Therefore, I'm closing the PR for now. Feel free to argue in favor of it being reconsidered, of course.

**Pull request closed without merging**
