### PR TITLE
Build a 'full' tarball next to the basic tarball.

### PR DESCRIPTION
**Pull request by thijskh**
In 2.0 many modules have been moved to external repositories and can be installed when needed. There's been some requests to also keep offering a 'fat' tarball which includes many modules ready to use by default. This change proposes to build such a tarball as part of the build process.

The list of modules to include is up for debate, currently more or less based on what was included in 1.19.

This is just an initial suggestion on how to approach this, comments welcome.

### CODE REVIEW

**Comment by thijskh** [comment]
Running it now gives some dependencies issues btw which I still need to investigate:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires simplesamlphp/simplesamlphp-module-authx509 ^1.1 -> satisfiable by simplesamlphp/simplesamlphp-module-authx509[v1.1.0].
    - simplesamlphp/simplesamlphp-module-authx509 v1.1.0 requires simplesamlphp/simplesamlphp-module-ldap ^1.2 -> found simplesamlphp/simplesamlphp-module-ldap[v1.2.0, ..., v1.2.17] but it conflicts with your root composer.json require (^2.1).
  Problem 2
    - Root composer.json requires simplesamlphp/simplesamlphp-module-consent ^1.1 -> satisfiable by simplesamlphp/simplesamlphp-module-consent[v1.1.0].
    - simplesamlphp/simplesamlphp-module-consent v1.1.0 requires simplesamlphp/assert ~0.2.13 -> found simplesamlphp/assert[v0.2.13] but it conflicts with your root composer.json require (^0.8.0).
  Problem 3
    - Root composer.json requires simplesamlphp/simplesamlphp-module-discopower ^1.2 -> satisfiable by simplesamlphp/simplesamlphp-module-discopower[v1.2.0].
    - simplesamlphp/simplesamlphp-module-discopower v1.2.0 requires simplesamlphp/composer-module-installer ~1.1.8 -> found simplesamlphp/composer-module-installer[v1.1.8] but the package is fixed to v1.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
  Problem 4
    - simplesamlphp/simplesamlphp-module-consentadmin v1.0.0 requires simplesamlphp/simplesamlphp-module-consent ^1.0 -> satisfiable by simplesamlphp/simplesamlphp-module-consent[v1.1.0].
    - simplesamlphp/simplesamlphp-module-consentadmin v1.0.1 requires simplesamlphp/assert ~0.2.7 -> found simplesamlphp/assert[v0.2.7, ..., v0.2.13] but it conflicts with your root composer.json require (^0.8.0).
    - simplesamlphp/simplesamlphp-module-consent v1.1.0 requires simplesamlphp/assert ~0.2.13 -> found simplesamlphp/assert[v0.2.13] but it conflicts with your root composer.json require (^0.8.0).
    - Root composer.json requires simplesamlphp/simplesamlphp-module-consentadmin ^1.0 -> satisfiable by simplesamlphp/simplesamlphp-module-consentadmin[v1.0.0, v1.0.1].
```

**Comment by thijskh** [comment]
@dnmvisser

**Comment by tvdijen** [comment]
I'm not a fan of doing this tbh... It will always lead to debate on why a module is or is not included.
We have already included composer in the tarball to ease module installation.

**Comment by tvdijen** [comment]
Regarding the dependency-issues; I've fixed most of them.. We have to bump the assert-lib to `v0.8` on every module. `authx509` is a different story; we have to make that compatible with `ldap` v2. Shouldn't be too much work.

**Comment by thijskh** [comment]
I don't see "discussion" as a bad thing per se. It should indeed be somewhat defensible what we do and do not include.

We can await 2.x release and see if we get feedback on the new minimal tarball.

**Comment by tvdijen** [comment]
Or we consider `full` to be 'all the modules within our namespace'?

**Pull request closed without merging**
