### PR TITLE
Updated Danish localisation in all files

### PR DESCRIPTION
**Pull request by larsnaesbye**
I took the liberty of fixing a few misspelt words in the Danish localisation.

### CODE REVIEW

**Comment by jaimeperez** [comment]
Hei @larsnaesbye!

Mange tak! Unfortunately, the way we provide translations (up until today) is not by changing the strings directly in the translation files. We use the [translation portal](https://translation.rnd.feide.no/) to collect all the localised strings in the different languages, and then when we have a new release, we regenerate the translation files automatically.

Would you be so kind to contribute your fixes there? I'd really appreciate :smile:

**Comment by larsnaesbye** [comment]
Sure. I'm sorry I didn't notice the translation portal :-)

**Comment by jaimeperez** [comment]
No problem at all, and thanks again!

**Comment by larsnaesbye** [comment]
I did some work on the Danish translation in the portal. Do you only generate the translation files upon new releases or does it happen during the development of the next version?

**Comment by jaimeperez** [comment]
Usually we do that when preparing for a new release, but if you really need the translations in master, we could apply the changes now.

**Comment by larsnaesbye** [comment]
Well, not right now, but when I've gotten around to about 100% it'd be nice :)

**Comment by jaimeperez** [comment]
Yep, I didn't mean *as we speak* :blush: 

Anyway, that's not a problem. Just let me know when you are ready :+1:

**Comment by larsnaesbye** [comment]
OK, gotten to 88% and I found a thing in the original (English) text that needs correction - 'an' instead of 'and' in help_text under dict-InfoCard. Where do I change that in the translation portal? :-)

**Comment by larsnaesbye** [comment]
I've done 100% of the Danish translation now. Would this be a good time to update the files? :-)

**Comment by jaimeperez** [comment]
Tak @larsnaesbye!

I've just updated the files with your translations :wink:

**Pull request closed without merging**
