### PR TITLE
Fixes issue 337

### PR DESCRIPTION
**Pull request by andres-blanco**
This fixes the issue 337.
I added a function getSelfHostWithout port to retain the original behaviour. 
I've also added some unit tests.

Cheers

### CODE REVIEW

**Comment by thijskh** [comment]
I think this is a good approach to fix #337.

I'm wondering if it would not be marginally better to have getSelfHostWithoutPort call getSelfHost and chop off any port.

**Comment by andres-blanco** [comment]
I think it's a matter of taste. For me, the normal behaviour is that the port is part of the host. 
But I think that you would be a better judge for the decision since you deal with hosts a lot more than me!
If you want, I'll make that change

**Comment by jaimeperez** [comment]
¡Muchas gracias Andrés!

Strictly speaking, the host is the DNS name or IP address where you can reach the server, and the port is more related to the TCP endpoint, not the host itself.

In any case, I think the most important thing to keep in mind is coherence, and also try to be explicit. We already have a method called `getSelfHostWithPath()`, so it makes sense to have a `getSelfHostWithPort()`, better than a variant **without**. Additionally, the method will not display standard ports (which I think makes sense), so I'd better be explicit about that, renaming it to `getSelfHostWithNonStandardPort()`. Quite long, but no room for misunderstandings :smile: 

I've done this changes myself, adapted (and completed) the test, and merged everything into master. Please confirm that the final code fixes issue #337.

**Comment by andres-blanco** [comment]
Everything works fine! 

Cheers!

**Pull request merged**
