### PR TITLE
Add support for returned config array in config files

### PR DESCRIPTION
**Pull request by cicnavi**
This PR aims to add support for returning config array in config files. For example, this would enable writing config like this:

```php
<?php

declare(strict_types=1);

return [
    'returned' => 'config',
];
```

Current way of defining $config variable remains functional.

### CODE REVIEW

**Comment by monkeyiq** [comment]
It looks like the CI doesn't like the new config files being in windows end of line mode.

**Comment by cicnavi** [comment]
Oh, totally missed that... It is fixed now.

**Comment by cicnavi** [comment]
Any chance to get this in v2.2.*?

**Comment by tvdijen** [comment]
I've just backported it. No release-date is available yet

**Comment by monkeyiq** [comment]
cool :)

**Comment by cicnavi** [comment]
Thank you!

**Pull request merged**
