### PR TITLE
Add authData

### PR DESCRIPTION
**Pull request by macmenco**
Make authData available in template

### CODE REVIEW

**Comment by tvdijen** [comment]
I've discussed this with Menco and he basically wants the output of /admin/test/{as} (behind admin-pass) that has a little more info, instead of /core/account/{as} (public)

I can see why we don't display the authData on the account-page, but perhaps we can add a /debug route for this on the account-page? Admins can send this link to users to provide debug-info and it would save Menco the trouble of overriding templates

**Comment by thijskh** [comment]
On the auth test it’s a collapsible. Why not do the same on the account oage but with a better description. E.g. “Show technical details” or “show debug information for use by support staff”

**Comment by tvdijen** [comment]
@thijskh Thanks, I totally agree..   @macmenco could you include an updated `auth_status.twig` to this PR? Be aware that this page is for end-users and that it shouldn't display scary debug-data by default (as it does in the admin-module)

**Comment by macmenco** [comment]
Sorry for the delay. I've added the requested change to display the extra info.

**Comment by tvdijen** [comment]
No worries, we have bigger priorities as you can imagine ;)

**Comment by tvdijen** [comment]
I took care if the comments now, but I'm not entirely happy with the result..

The way it is now:

afbeelding

What I'd prefer:

afbeelding

However, I cannot think of an easy way to get rid of the 'general'-block of the Expander-template.. Any suggestions @thijsk or @jaimeperez ?

**Comment by jaimeperez** [comment]
Yeah, I've been there as well. Maybe we should make an alternative expander HTML layout for cases like this, where there's no block at all? Then we can just embed that one instead.

**Comment by tvdijen** [comment]
We can do this easier:  https://stackoverflow.com/a/13806784

**Comment by jaimeperez** [comment]
That's a good option actually, having some little logic in the template itself to decide what kind of widget is needed. However, I think we need a little bit more than just skipping the block with the visible contents, as in that case we would just have another block that we use to expand it, and it would look weird, IMO. Maybe drop the border of that block, and also remove padding from the hidden contents?

In any case, I think it's worth exploring this path and testing how it looks if we just skip the top block.

**Comment by jaimeperez** [comment]
Hi!

I've taken the liberty to do a few modifications myself. This is how it would look like now, taking advantage of what we already have in other places:

image

**Comment by jaimeperez** [comment]
@tvdijen does it look good? Shall we merge?

**Comment by tvdijen** [comment]
Excellent, thanks!

**Pull request merged**
