### PR TITLE
base: Migrate www-scripts to Controllers

### PR DESCRIPTION
**Pull request by tvdijen**
Needs tests + _testing_

### CODE REVIEW

**Comment by tvdijen** [comment]
I think it might make sense to move these controllers to the saml-module since they both deal with SAML-endpoints

**Comment by thijskh** [comment]
Functionally it should be right to move these to the saml module. Whether that's easy to achieve though, I'm not certain. You could merge this now since it improves over the previous situation.

**Comment by tvdijen** [comment]
It's fairly easy to do so.. It's just that we need to keep the legacy routes in the base..
I'll move them and add tests before I merge

**Comment by tvdijen** [comment]
I see one issue that we need to discuss.. By migrating to controllers we've basically changed all of our endpoints. We have legacy routes in place for that for backwards compatibility, however the metadata-endpoint is also our entityID and I don't think we can solve that one without pain.  Changing the entityID would mean that upgrading to 2.0 implies exchanging metadata with your peers..

**Pull request merged**
