### PR TITLE
Deprecate assert with string

### LINKED ISSUE #573: assert() with string as the assertion is DEPRECATED as of PHP 7.2
Just a heads up. From http://php.net/manual/en/function.assert.php 

Using string as the assertion is DEPRECATED as of PHP 7.2.

SSP is littered with assertions taking a string argument.

### PR DESCRIPTION
**Pull request by fentie**
Fixes #573

Removed string-based usage of assert. Where applicable in the assert calls, I also replaced `is_null` with `=== null`, double quotes to single quotes (to match style elsewhere) and lowercased PHP constants (false/null)

### CODE REVIEW

**Comment by jaimeperez** [comment]
Thanks **so much** for this @fentie! This is an awesome contribution, you just saved us plenty of hours of work!

**Comment by fentie** [comment]
No problem at all. It was mostly regex search & replace 😀

**Comment by bradjones1** [comment]
This appears only committed to master, not the 1.x branches? I tried to find an explanation of the branching strategy but came up empty, can a maintainer shed some light on whether this will be in 1.x or if it should be applied as a patch until then? Thanks.

**Comment by thijskh** [comment]
This will be part of 1.16 when that’s released.

**Comment by alberto56** [comment]
Hi all, when I try to apply this as a patch to the current latest version, I get:

    curl -O https://patch-diff.githubusercontent.com/raw/simplesamlphp/simplesamlphp/pull/708.patch
    patch -p1 < ../708.patch

    ...
    patching file modules/saml/lib/Auth/Process/FilterScopes.php
    patching file modules/saml/lib/Auth/Process/NameIDAttribute.php
    Hunk #3 FAILED at 105.
    1 out of 3 hunks FAILED -- saving rejects to file modules/saml/lib/Auth/Process/NameIDAttribute.php.rej
    patching file modules/saml/lib/Auth/Process/PersistentNameID.php
    patching file modules/saml/lib/Auth/Process/PersistentNameID2TargetedID.php
    ...
    
modules/saml/lib/Auth/Process/NameIDAttribute.php.rej contains:

    --- modules/saml/lib/Auth/Process/NameIDAttribute.php
    +++ modules/saml/lib/Auth/Process/NameIDAttribute.php
    @@ -105,16 +105,16 @@ private static function parseFormat($format)
          */
         public function process(&$state)
         {
    -        assert('is_array($state)');
    -        assert('isset($state["Source"]["entityid"])');
    -        assert('isset($state["Destination"]["entityid"])');
    +        assert(is_array($state));
    +        assert(isset($state['Source']['entityid']));
    +        assert(isset($state['Destination']['entityid']));
     
             if (!isset($state['saml:sp:NameID'])) {
                 return;
             }
     
             $rep = $state['saml:sp:NameID'];
    -        assert('isset($rep["Value"])');
    +        assert(isset($rep['Value']));
     
             $rep['%'] = '%';
             if (!isset($rep['Format'])) {

If anyone can suggest a way around this I'd be grateful, thanks!

**Comment by thijskh** [comment]
Edit the file by hand?
Just ignore the deprecation notices as they’re only notices? Turn them off in PHP config?

**Comment by alberto56** [comment]
There is one line which has changed and makes the patch not apply. Here is a version of the patch which can work if anyone needs it. Use with caution!

[708-modified-for-2018-05-23-15-59-22.patch.tar.gz](https://github.com/simplesamlphp/simplesamlphp/files/2032642/708-modified-for-2018-05-23-15-59-22.patch.tar.gz)

**Pull request merged**
