### PR TITLE
Skip disco when single IdP found

### PR DESCRIPTION
**Pull request by thijskh**
When there's only a single IdP to choose from, discovery is useless at best and confusing at worst. Just skip it as we know what the choice will be.

### CODE REVIEW

**Review by tvdijen — APPROVED** [review]

**Comment by monkeyiq** [comment]
I tested this using sspsmall and changing authsources/`sp.idp == null;` 

Without the patch I was offered a disco screen with a choice of 1 IdP with the patch I was directed straight to the IdP.

When I had just one IdP for an SP I would generally state it on the SP page so hadn't noticed this degenerate case. I imagine in real world cases where the IdP list might be defined in a more complex way then this case would also present itself and offer a less than desirable user experience.

**Comment by monkeyiq** [comment]
I have picked this into master https://github.com/simplesamlphp/simplesamlphp/commit/f7fb7bb099c5bb09c1d8717f9cd9d5befbb35afc

**Comment by monkeyiq** [comment]
This seems like a candidate for picking back into the 2.3 series as well?

**Comment by thijskh** [comment]
It has worked in the previous way since day one I guess. So maybe it's more like a feature than an actual bugfix.

**Pull request merged**
