### PR TITLE
AttributeAlter:  Add option to merge target attribute values

### PR DESCRIPTION
**Pull request by tvdijen**
Use case for this would be to run two consecutive AttributeAlter filters using different source attributes, but the same target-attribute. It is implemented in a backwards compatible way, however, I feel that merging would be the logical default.

### CODE REVIEW

**Review by thijskh — COMMENTED** [review]
Good addition, but also good to keep it BC. Given the many `if` branches now in the auth proc filter that this further increases, this must have unit tests to remain maintainable.

**Comment by tvdijen** [comment]
Please see if my changes make sense.. I'll try to add tests later tonight

**Comment by thijskh** [comment]
Yes, I think it should be OK but indeed, so many ifs, tests are welcome

**Comment by tvdijen** [comment]
I kinda need this like.. yesterday..  It's not exactly semver, but would you mind if I backport this to 1.19.6?

**Review by thijskh — APPROVED** [review]

**Comment by thijskh** [comment]
Well, isn't the easiest/cleanest way to provide it in 1.19 as a module?

**Comment by tvdijen** [comment]
What do you mean? The authproc already exists in 1.19.. I only added the merge-flag..
Are you suggesting that I should make a custom module to use this functionality in 1.19?

**Comment by thijskh** [comment]
Isn't that a simple solution without requiring to backport this to 1.19? Just copy the file, basically?

**Comment by tvdijen** [comment]
It's not a sustainable solution, but I'll guess I'll have to deal with it (and hope I don't forget about it the next time I deploy an update)..

**Pull request merged**
