### PR TITLE
Add PHP 7.2 into Travis

### PR DESCRIPTION
**Pull request by Trejjam**

### CODE REVIEW

**Comment by Trejjam** [comment]
Are there any reason why is committed composer.lock file?

**Comment by thijskh** [comment]
Good to see this is already catching some actual bugs!

The discussion about composer.lock is probably best had in #628

**Comment by Trejjam** [comment]
Actually, it is no longer a bug, because of merged fix in [saml2](https://github.com/simplesamlphp/saml2/pull/111). The only bug is a presence of the lock file in a library and maybe not using master of saml2 in tests.

**Comment by Trejjam** [comment]
Hi, @thijskh 

please take a look.

**Comment by thijskh** [comment]
Thanks!

**Pull request merged**
