### PR TITLE
Patch to have ownCloud/user_saml work

### PR DESCRIPTION
**Pull request by deltafunction**
when using simplesamlphp with the default PHP session store

### CODE REVIEW

**Comment by deltafunction** [comment]
Any progress on this?

**Comment by jaimeperez** [comment]
Hi @deltafunction!

Thanks a lot for your patch and my apologies for the delay. Could you elaborate a little bit on what's exactly the problem you are solving here, and why your patch is needed?

**Comment by thijskh** [comment]
@deltafunction Could you clarify the intention? I must say that it's also not evident to my why this change is needed.

**Comment by thijskh** [comment]
Could it be that this problem is the same as the one in #260, @deltafunction?

**Comment by deltafunction** [comment]
It looks related yes. Let me try out the patch or, preferably, a new
release with the patch, and get back to you.

**Comment by thijskh** [comment]
We'd prefer to know if the patch solves your problem before we create a release :)

**Comment by jaimeperez** [comment]
Hi @deltafunction!

Were you able to test this out?

**Comment by deltafunction** [comment]
Hi,

I tried out the 1.14.0-rc1 tarball and it does not fix my problem. I get the usual "Session information lost" (or something along those lines).

**Comment by thijskh** [comment]
I'm still a bit in doubt about this, because we don't have a clear understanding about what ownCloud specifically does that causes the problem (and is not a problem with other SPs), and therefore cannot judge whether the proposed solution is the right way to go.

**Pull request closed without merging**
