### PR TITLE
Document cron module

### PR DESCRIPTION
**Pull request by pradtke**
@thijskh I opted to do the cron documentation as a separate PR and then I can update PR-685 to document the new features once this is merge.

I was unsure how to build the documentation to verify that the links from `automated metadata` to `cron` were correct.

### CODE REVIEW

**Comment by thijskh** [comment]
Yes, this looks fine. Also not sure about the links, but looking at other places in the docs, they do the same. @jaimeperez probably knows how the documentation is built so those links resolve.

**Comment by jaimeperez** [comment]
The links are relative from the current path, and for documentation in modules, the last part of the URL should be in the form `<name of the module>:<name of the file>`, so `cron:cron` would translate to a document called `cron.md` located in `modules/cron/docs/`.

**Comment by thijskh** [comment]
Alright, seems fine then!

**Comment by pradtke** [comment]
@thijskh I did a quick grep of the existing convention using `grep -r '](.*:.*)' docs/ | grep -v 'http'`
The vast majority (all but one link) of the markdown links from `docs` into modules start with `./`.

Should I still remove the `./`? or should I keep it to match existing docs?

**Comment by jaimeperez** [comment]
Actually, without the `./` in front, the links won't work. Haven't tested with other browsers than Chrome, but at least with that one, if the `./` is missing at the front of the link, the browser won't follow it.

I've just fixed a couple broken links, in fact.

**Pull request merged**
