### PR TITLE
Avoid memcache data collision

### PR DESCRIPTION
**Pull request by tvdijen**
Avoid memcache data collision when running multiple SSP instances on the same host

### CODE REVIEW

**Comment by thijskh** [comment]
Hi Tim,

Thanks, this seems like a useful change to have.

I'm wondering if it wouldn't be nicer to fetch the config value in `SimpleSAML_Store_Memcache`'s constructor and use it in each of the methods?

Also I'm not so sure about the four commits, which all do not have a really descriptive commit message. Maybe you can rebase them into two (one for the purely functional change, one for the coding style changes)?

**Comment by tvdijen** [comment]
Hi Thijs, I'll do that and see if I can put it in the constructor as you said.. I'll make it a new PR then

**Comment by thijskh** [comment]
You need not make a new PR; you can instead force-push to the branch you used to make the PR.

**Comment by tvdijen** [comment]
Hehe, well, I guess it's too late for that now.. I should probably read a bit about version control, because sometimes it makes no sense to me at all...

**Pull request closed without merging**
