### PR TITLE
Add Greek support

### PR DESCRIPTION
**Pull request by NicolasLiampotis**
This PR adds Greek support to SimpleSAMLphp and includes translations for:
* IdP discovery pages
* user consent page
* common attributes, including the `eduPerson` profile
* login/logout UI

### CODE REVIEW

**Comment by thijskh** [comment]
LGTM :+1:

**Comment by jaimeperez** [comment]
Ευχαριστώ @NicolasLiampotis!

I see a couple of issues with this PR. One is that there's no name for the language in `templates/includes/header.php`, so even though the language is added to the list of languages available in `config.php`, it will never show because there's no name defined for it.

The other is that adding it to the list of languages available, once fixed the previous issue, would allow users to switch to it. However, just a few parts of the web interface is translated, mostly those for end users. While that's ok, we would really appreciate to have the entire web interface translated to Greek.

Would that be too much to ask for?

**Comment by NicolasLiampotis** [comment]
Παρακαλώ @jaimeperez :-)

> One is that there's no name for the language in templates/includes/header.php, so even though the language is added to the list of languages available in config.php, it will never show because there's no name defined for it.

Actually, the language name for `el` is already included in `header.php` (see [line 173](https://github.com/simplesamlphp/simplesamlphp/blob/4c68e5eaafe95131673333030e6752f8056b72ab/templates/includes/header.php#L173))

> The other is that adding it to the list of languages available, once fixed the previous issue, would allow users to switch to it. However, just a few parts of the web interface is translated, mostly those for end users. While that's ok, we would really appreciate to have the entire web interface translated to Greek.

Yes, will definitely finalise the translation as soon as I find the time. For now, as you said, this PR mostly covers the end-user UI.

**Comment by jaimeperez** [comment]
> Actually, the language name for el is already included in header.php (see line 173)

Uhm, you are absolutely right. I didn't see it at the end of the list, so I thought it wasn't there. Still, the reason why I was looking there was that I wasn't getting the language listed in the list, but now I see it's not the only one, and it's apparently related to a theme that we are using. I'll have to look more into that...

Thanks for the feedback and for contributing!

**Comment by thijskh** [comment]
@NicolasLiampotis I see that you've been adding more commits, nice.
My opinion is that this can be merged any time, covering the end user UI is the most important,, agree @jaimeperez? Anything stopping us from merging it?

**Comment by jaimeperez** [comment]
Don't know, to be honest. If the translation of all the strings in the UI is completed, then I think we can merge it, yes.

**Comment by NicolasLiampotis** [comment]
According to the (ugly) script attached, Greek translation coverage has reached 70%:
```
$ ./transcov.sh el
./dictionaries/admin.definition.json [51/52]
./dictionaries/attributes.definition.json [22/48]
./dictionaries/disco.definition.json [7/7]
./dictionaries/errors.definition.json [13/79]
./dictionaries/login.definition.json [21/22]
./dictionaries/logout.definition.json [18/18]
./dictionaries/status.definition.json [13/13]
./modules/authorize/dictionaries/Authorize.definition.json [2/2]
./modules/authX509/dictionaries/X509error.definition.json [2/2]
./modules/authX509/dictionaries/X509warning.definition.json [5/5]
./modules/authYubiKey/dictionaries/yubikey.definition.json [2/2]
./modules/consent/dictionaries/consent.definition.json [21/22]
./modules/consentAdmin/dictionaries/consentadmin.definition.json [0/21]
./modules/core/dictionaries/frontpage.definition.json [48/48]
./modules/core/dictionaries/no_cookie.definition.json [3/3]
./modules/core/dictionaries/no_metadata.definition.json [5/5]
./modules/core/dictionaries/no_state.definition.json [11/11]
./modules/core/dictionaries/short_sso_interval.definition.json [3/3]
./modules/cron/dictionaries/cron.definition.json [8/8]
./modules/discopower/dictionaries/tabs.definition.json [12/12]
./modules/expirycheck/dictionaries/expwarning.definition.json [11/11]
./modules/memcacheMonitor/dictionaries/memcachestat.definition.json [19/19]
./modules/multiauth/dictionaries/multiauth.definition.json [2/2]
./modules/negotiate/dictionaries/negotiate.definition.json [5/5]
./modules/preprodwarning/dictionaries/warning.definition.json [3/3]
./modules/saml/dictionaries/wrong_authncontextclassref.definition.json [2/2]
TOTAL: [309/425] 72.7%
```

So, yes, currently this PR covers most of the UI and could be merged any time. But perhaps we could wait a few days until all the missing translations are there.

[transcov.sh.txt](https://github.com/simplesamlphp/simplesamlphp/files/179774/transcov.sh.txt)

**Comment by NicolasLiampotis** [comment]
Greek translation should be considered complete:
```
$ ./transcov.sh el
./dictionaries/admin.definition.json [51/52]
./dictionaries/attributes.definition.json [48/48]
./dictionaries/disco.definition.json [7/7]
./dictionaries/errors.definition.json [75/79]
./dictionaries/login.definition.json [21/22]
./dictionaries/logout.definition.json [18/18]
./dictionaries/status.definition.json [13/13]
./modules/authorize/dictionaries/Authorize.definition.json [2/2]
./modules/authX509/dictionaries/X509error.definition.json [2/2]
./modules/authX509/dictionaries/X509warning.definition.json [5/5]
./modules/authYubiKey/dictionaries/yubikey.definition.json [2/2]
./modules/consent/dictionaries/consent.definition.json [21/22]
./modules/consentAdmin/dictionaries/consentadmin.definition.json [21/21]
./modules/core/dictionaries/frontpage.definition.json [48/48]
./modules/core/dictionaries/no_cookie.definition.json [3/3]
./modules/core/dictionaries/no_metadata.definition.json [5/5]
./modules/core/dictionaries/no_state.definition.json [11/11]
./modules/core/dictionaries/short_sso_interval.definition.json [3/3]
./modules/cron/dictionaries/cron.definition.json [8/8]
./modules/discopower/dictionaries/tabs.definition.json [12/12]
./modules/expirycheck/dictionaries/expwarning.definition.json [11/11]
./modules/memcacheMonitor/dictionaries/memcachestat.definition.json [19/19]
./modules/multiauth/dictionaries/multiauth.definition.json [2/2]
./modules/negotiate/dictionaries/negotiate.definition.json [5/5]
./modules/preprodwarning/dictionaries/warning.definition.json [3/3]
./modules/saml/dictionaries/wrong_authncontextclassref.definition.json [2/2]
TOTAL: [418/425] 98.3%
```
This PR can finally be merged (unless the coverage decrease is a blocker)
/cc @jaimeperez @thijskh

**Comment by jaimeperez** [comment]
Thanks so much Nicolas for such an amazing job!

At this moment we are evaluating alternatives for the old translation system, and we are playing a bit with transifex, where you can have translators and people coordinating translations of a specific language (as well as validating them). If we end up using it, would you mind to help us out coordinating greek translations?

**Comment by NicolasLiampotis** [comment]
Sure, you can count me in!

**Comment by jaimeperez** [comment]
Great! Thanks a lot!

**Pull request merged**
