### PR TITLE
Import the conditional authproc-filters

### LINKED ISSUE #1693: Conditional authproc filters
I'm successfully using **Second Factor Only (SFO)** from https://github.com/OpenConextApps/simplesamlphp-module-stepupsfo. That is implemented by configuring a few authproc filters in sequence.
Configuring the authproc filter means that the second factor functionality is enabled for everyone.
It would be good if authproc filter(s) could be made conditional, for instance on the presence/absence of specific attributes.
This would allow a phased approach, for example only apply SFO to users that are part of a specific group in our directory.
Once this is running without problem, require more groups, and eventually to everyone.

### LINKED ISSUE #1766: Conditional AuthProcFilter
**Problem**
I didn't find an easy way to support the REFEDS Assurance Framework and MFA without a third-part module developed by CIRRUS[1]. Their module allowed me to respect the requirements about the AuthnContextClassRef that an IdP and an SP have to respect for asking and answering MFA. 
The Request (SP) and the Response (IdP) have to contain the right value of AuthnContextClassRef **only if** they ask/provide a MultiFactorAuthentication. 
CIRRUS has implemented an easy way to use one or another AuthProcFilter through a condition and this made possible to address the REFEDS Assurance Framework. Their module allow me to activate an AuthProcFilter only on a specific condition: if an SP requests MFA, than the IdP answers with MFA, else... The IdP answers with a username/password login page only. 

https://github.com/cirrusidentity/simplesamlphp-module-cirrusgeneral/#phpconditionalauthprocinserter

**Describe the solution you'd like**

I ask to do the same with only official SimpleSamlPhp code. I hope to find an official way to use the AuthProcFilters conditionally to be able to manage different behaviors of SPs or other. 

**Describe alternatives you've considered**
I didn't find any other easy solution other than CIRRUS Plugin:

https://github.com/cirrusidentity/simplesamlphp-module-cirrusgeneral/#phpconditionalauthprocinserter

### PR DESCRIPTION
**Pull request by tvdijen**
Taken from cirrusidentity/simplesamlphp-module-general with thanks to @pradtke 

Closes #1693
Closes #1766

### CODE REVIEW

**Comment by tvdijen** [comment]
I'm wondering if we could or _should_ provide a better way for people to manipulate the authproc-chain, instead of using a ReflectionClass here

**Comment by pradtke** [comment]
@tvdijen hmm, interesting approach.  a couple of our use cases are using the if-else capability in the cirrus module version, and being able to insert multiple authproc filters for a single condition.  For `if-else` it is often to insert different sets of filters so I don't think it would be something that could be added to the `ProcessingChain` directly.

I do like that with your alternative approach it can be enabled for any authproc without needing to wrap it. Though I would request that you use a different method name than `checkCondition()`  - solely for my selfish reason that `ConditionalProcessingFilterInserter` currently uses that name with `if-else` semantics, and it will make my life easier for module maintenance if SSP doesn't interpret that method with just `if` semantics. 

I don't know if people using `ConditionalProcessingFilterInserter` are using it more for the simpler case that `6f7b3e3` addresses, or using it for more complex use cases.

I agree with your point about not using reflection if the `ConditionalProcessingFilterInserter` is incorporated into SSP. Perhaps incorporating the methods from `ProcessingChainRuleInserter` into `ProcessingChain` would address that?

I'm out for 2 weeks, so may not respond to anything for awhile (and apologies if I missed any existing question in here).

**Comment by tvdijen** [comment]
Thanks @pradtke !
To sum things up, I'll continue with this new approach, rename the `checkCondition` for your convenience and merge the two methods from your `ProcessingChainRuleInserter` into our `ProcessingChain`

**Review by marioheber — APPROVED** [review]

**Comment by tvdijen** [comment]
Well that's uncalled for :')

**Comment by marioheber** [comment]
> Well that's uncalled for :')
Hey there, sorry.

**Comment by tvdijen** [comment]
> Hey there, sorry.

No worries, I just think it's strange.
I don't take reviews without any comments from random persons.
I need a review from my fellow devs and no one else.

**Comment by tvdijen** [comment]
@pradtke I think your holidays are over by now.. How does this look to you?

**Comment by pradtke** [comment]
@tvdijen I think this looks really good. Thank you for taking this forward and getting it incorporated.

**Pull request merged**
