### PR TITLE
Integrate sanitycheck hook into admin module

### PR DESCRIPTION
**Pull request by thijskh**
The sanitycheck module overlaps the config check functionality in the admin module. Make it one place where the results of all sanity checks are shown. This is done in admin so the user does not need to install a separate module for this - that will no doubt lead to most checks never being ran.

The change kept the existing sanitycheck hook format, so all modules implementing this hook will work out of the box without changes required.

The 'core' module hooks have been removed since the checks duplicate already present checks in the config page.

As an example, the saml-specific checks have been moved from the admin to saml module.

More changes are possible, e.g. the check for LDAP could be moved to the ldap module so it's only shown if you actually use LDAP. Etc.

An alternative approach would be to keep the sanitycheck module, make it part of the core module set, and move all existing checks in the admin module into sanity check hooks.

### CODE REVIEW

**Review by tvdijen — APPROVED** [review]
Excellent work! Just a few sniffer-issues to fix and then merge!

**Comment by tvdijen** [comment]
This btw is something that should be well documented in upgrade notes.

**Comment by tvdijen** [comment]
That this functionality has become implicit and it's no longer required to install the sanitycheck-module?

**Comment by thijskh** [comment]
Yes. Although it doesn’t hurt if you keep it.

**Comment by tvdijen** [comment]
Should I add this to the 2.1 release?

**Comment by thijskh** [comment]
I don't see why not. It's simple and indeed does not break anything existing.

**Pull request merged**
