### PR TITLE
Fix for #618, correcting the login layout on mobile screens.

### PR DESCRIPTION
**Pull request by poikilotherm**
As mentiond in #618, a PR :-)

Feel free to request changes. Would be glad to see this merged.

### CODE REVIEW

**Comment by poikilotherm** [comment]
Sorry for the noise... Is there any particular reason this really simple and small fix is not yet merged?

**Comment by jaimeperez** [comment]
Hi @poikilotherm!

First of all, thanks a lot for the PR and sorry for the delay. Basically, it's not merged because I haven't been able to look at it yet. That, and also that we are working in a new template system and user interface, so this kind of fixes get low priority because they will be temporary...

**Comment by thijskh** [comment]
Tested it, could reproduce the original problem and that your change fixes it, on two browsers on desktop and two browsers on mobile. Thanks!

**Comment by jaimeperez** [comment]
Thanks Thijs!

**Pull request merged**
